on:
  schedule:
    - cron:  '20 3,15 * * *'

name: Render README

jobs:
  render:
    name: Update Data and README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/Library/Application Support/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install rmarkdown
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "data.table", "jsonlite", "renv"))'
          Rscript -e 'install.packages(c("RCurl", "magrittr", "here", "ggplot2"))'

      - name: Data updates
        run: Rscript -e 'source("R/01_COVID-19_PT_data.R")'

      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'

      - name: Commit results
        run: |
          git config user.email "ceaul@users.noreply.github.com"
          git config user.name "ceaul"
          git add README.md README_figs/* data/* data-raw/*
          git commit -m 'Data Update & Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
